### ISSUE TITLE
Enable HTML <script> syntax highlight

### ISSUE THREAD

**Issue by andremw** [refined-bitbucket/refined-bitbucket#1]
The inline <script> tags are not being highlighted as expected.

It looks like that it can be accomplished using Prism's [Show Language Plugin](http://prismjs.com/plugins/show-language/), but I tried that and the style got messed up again.

So I think it's more important to fix the CSS problem (to be able to remove the styles added in the source-handler.js and use the .css files) and then try to solve this problem (the prism.css probably solves it)

**Comment by reyronald** [comment]
I'm not sure I understand correctly. 

I believe this happens because the extension is highlighting the contents of the script tag as HTML instead of JavaScript because the extension of the file is `.html`, not sure how the mentioned plugin could correct that.

If that's what this issue is about, then I'm afraid is not trivial since the highlighting occurs on a line-by-line basis, so Prism has no context and is not aware that the current line might be inside a script tag. I guess it certainly could be fixed by ourselves with some algorithmic checks, but I don't think it's worth it.
