### ISSUE TITLE
Missing syntax highlighting for swift?

### ISSUE THREAD

**Issue by TimAEllis** [refined-bitbucket/refined-bitbucket#147]
It seems you have the capabilities for swift but haven't included it in the export. (NB: I haven't actually tested this with swift yet so it may be there. I just noticed the inconsistency with ".swift" missing)

**Comment by reyronald** [comment]
The export you mention doesn't actually represent all of the languages the extension is able to highlight!

It just includes those extensions that don't exactly match the name of the alias provided by PrismJS, check them all here: http://prismjs.com/index.html#languages-list

In the specific case of Swift, since the extension for swift files is `.swift`, and the name of the alias provided by PrismJS is `swift`, it's not necessary to include it in that list! So it should work right off the bat.
