### ISSUE TITLE
New logo / icon

### ISSUE THREAD

**Issue by andremw** [refined-bitbucket/refined-bitbucket#15]
It would be very nice if we had a logo and a beautiful extension icon. I'm definitely not good with drawing and coloring, so _help wanted_. lol
This is not supposed to be a syntax highlight project only, so the current icon is not the most appropriate.

**Comment by reyronald** [comment]
I had a designer friend of mine @alfonsote sketch some ideas, would love to hear the opinions of the user base!

**Option 1**

![option-1](https://user-images.githubusercontent.com/7514993/36678383-f513f804-1ae6-11e8-876a-57b629682be9.png)

**Option 2**

![option-2](https://user-images.githubusercontent.com/7514993/36678398-fb87631a-1ae6-11e8-8fdb-8937bc9e34a8.png)

**Comment by clarkd** [comment]
I've been using this plugin for quite some time and would love to give something back. I'm a front-end designer so have put together a few more logo ideas for you!

I noticed the above was using Bitbucket's old logo so tried to pull in aspects of Atlassian's new branding here without completely copying their work!

These first two work quite well I think, but would need some tweaking to get into a usable small icon format. Perhaps just using the "bucket" icon would be enough...
![idea1](https://user-images.githubusercontent.com/3793131/36698415-b2d70296-1b41-11e8-8396-a90dc4cef1c2.png)

![idea2](https://user-images.githubusercontent.com/3793131/36698423-b771151c-1b41-11e8-8cc7-4488e49d40e4.png)

This second idea is a quite cool integration of the "R" and "B" and workable in any size. 
![idea3](https://user-images.githubusercontent.com/3793131/36698431-be2692a6-1b41-11e8-89f2-b77bef0e7909.png)

Let me know your thoughts!

**Comment by dpekkle** [comment]
I'm mostly thinking in terms of the extension icon but the RB from clarkd or the icon from option 2 look nice.

**Comment by reyronald** [comment]
Hey @clarkd , those look amazing!! I would be perfectly happy with any of the options!

Although as @dpekkle says, we would need to come up with a smaller version of the logo as a whole to be used as the icon, which can be as small as 16x16 px (see https://developer.chrome.com/apps/manifest/icons), so that's something to take into account! 

If you'd like to submit a pull request to include them, just drop five PNG files for the icons of square sizes 16, 32, 48, 64 and 128 in the `src` folder, and a full size one in the root to be used in the README and anywhere else. This last one can be in another format if you prefer.

Finally we will have a professional looking presentation for the extension! 😅

**Comment by clarkd** [comment]
Hey @reyronald, glad you like them!

If you're happy to, we'll go with the RB logo for all the icons, and you can then use the larger format "REFINED BITBUCKET" for the README, App store etc?

I'll prep a PR tomorrow!

**Comment by reyronald** [comment]
@clarkd That sounds great! Looking forward to the PR! 😃
