### ISSUE TITLE
option to skip onInstalled window.open

### ISSUE THREAD

**Issue by jettero** [refined-bitbucket/refined-bitbucket#167]
Because of chrome sync, I have this plugin in 5 browsers around the room. This project updates a lot, so I get a window.open('https://github.com/refined-bitbucket/refined-bitbucket/releases/latest') on 5 browsers every couple days.

Could we get an option to disable the news feed?

I forked and found the relevant onInstalled.addListener(); but it's not clear how to get at the options in there, since they don't seem to be loaded yet at that point.

Ideas on how I could approach the patch or comments about why such a patch would be un-welcome are all welcome comment.

**Comment by reyronald** [comment]
Hey @jettero , I'm sorry I somewhat interrupted your work flow with the updates! 😢 There were indeed a few consecutive releases in the last few days because of some serious bugs found in one of the new features, I apologize!

Addressing your specific question, yes, it is possible to introduce an option to disable this and it's not difficult at all, it would only take a few lines of code! I'll make sure that it is available starting with the next release. I can either do this myself or guide you in the process if you have a special interest in contributing.

**Comment by jettero** [comment]
Hey, thanks for that.

I don't have any special interest in contributing, no. I don't mind contributing though. If it's simpler to do than explain and you're cool with doing it: go for it.

**Comment by nikoladev** [comment]
Would it be possible to subscribe to updates in a less intrusive way? I'd like to know what changed, but without a new tab popping up randomly.

I like the way Refined Github handles it: https://github.com/sindresorhus/refined-github/issues/1137

Or maybe a small 'unread messages dot' on the extension icon?

**Comment by reyronald** [comment]
@nikoladev Both of those are great ideas! 

I will tackle the notification badge on the extension icon when I'm done solving some of the current bugs with one of the latest features. You can open a separate issue for that if you want.

Thank you!

**Comment by jettero** [comment]
@nikoladev I love that idea. I do want to see the changes. It's just a pet peve over here. I've been looking for years for an extension that would prevent extensions from opening unsolicited tabs after an update.

**Comment by reyronald** [comment]
@jettero @nikoladev Subscribe to #182 !

Will be posting the updates there on each release as well!

Thanks for the idea again 👍

**Comment by nikoladev** [comment]
Thanks for implementing it so quickly!
