### ISSUE TITLE
Bad side-by-side scrolling performance with syntax highlighting enabled

### ISSUE THREAD

**Issue by Daanvm** [refined-bitbucket/refined-bitbucket#183]
The scrolling performance in a side-by-side window becomes really bad sometimes when highlighting is enabled. It's not uncommon for the CPU to hit over 100%, which causes the scrolling to freeze. It doesn't really seem related to the file size, it also happens for files of about 200 to 300 lines.

![screen shot 2018-03-14 at 14 06 31](https://user-images.githubusercontent.com/1397121/37404844-4fadb13e-2793-11e8-82ac-64b605eb94a2.png)

If I understand the Google Chrome profiler correctly, then most of the time is spend on the line [`Prism.highlightElement(preElement);`](https://github.com/refined-bitbucket/refined-bitbucket/blob/1bdc64b4e40ee01c85405ec41a7de6f0522ad1e2/src/syntax-highlight/syntax-highlight.js#L75). This seems to be triggered by the scrolling event.

![screen shot 2018-03-14 at 14 26 08](https://user-images.githubusercontent.com/1397121/37405095-1265bfaa-2794-11e8-82fc-bb94bbeaf001.png)

I haven't looked into it any further, as I don't really understand why the highlighter should run each time someone scrolls. But it would be great if this could be improved somehow.

**Comment by reyronald** [comment]
Hey @Daanvm! 

I don't use side-by-side very much so I probably wouldn't have noticed this myself, thank you for the in-depth analysis!

I will be taking a look at this to see if it's trivial enough to be pushed into the next release. Hope it is not causing you too much trouble in the mean time.

**Comment by Daanvm** [comment]
Thanks! The cpu usage of the side-by-side diff isn't really great anyway, even without any plugins active. So maybe there isn't a perfect solution.

I'll use the normal diff view in the meantime. Thanks for your great work in this plugin!

**Comment by nickpeirson** [comment]
Hey @reyronald, I was subscribed to this issue as I'm experiencing it as well, but previously I didn't want to just add a 'me too' comment. I saw that you'd tagged it as an enhancement, however for me this is a blocker. I use side by side view regularly and if I turn on syntax on it becomes completely unusable, stalling chrome for tens of seconds at a time when I try to scroll, so for me it's definitely a bug rather than an enhancement. I also wonder if other people are running into this and just quietly disabling the plugin, or uninstalling, it without reporting the issue.

I'm still using RB with syntax highlighting disabled, but it was the reason I started using it so it would be great to get it back again.

Thanks for the great plugin!

**Comment by reyronald** [comment]
Hey @nickpeirson , thanks for dropping by and letting me know your stance on this!

I certainly hope not many people are uninstalling the extension just because of this. That's why I made every feature optional through the Options page, so that the user would have a choice when this type of circumstances arise.

This is indeed blocking for the side-by-side highlighting, but not for the entire syntax highlighting feature since you could still have that enabled and use it if you don't regularly open the side-by-side panel, which is my personal case, and the reason why this hasn't been solved sooner. That's also why I labeled it as enhancement instead of bug.

That said, I was still planning to invest some time on this before the next release, but will prioritize it more now that you've stated how much of an inconvenience it can represent, I apologize for it!

**Comment by reyronald** [comment]
@Daanvm @nickpeirson I just released a new version (v3.12.0) with a fix for this. I would appreciate it if you could report back and let me know if you notice the difference. Since I don't use the side-by-side feature of Bitbucket often myself I don't have much reference to go on, although in my tests I did feel an improvement.

Looking forward to your comments!

**Comment by nickpeirson** [comment]
Hey @reyronald, thanks for the update.

I've done few quick tests and it's looking better so far. With it enabled, looking at pretty much any side by side diff with syntax highlighting enabled would lock up Chrome, however I've tried a few diffs with the latest extension version and it's remained mostly responsive. May be a couple of small stalls still, but nothing like the previous lockups I was seeing.

I'll keep an eye on it throughout the week and see if I hit any diffs that still cause problems, but so far so good! Thanks very much!

**Comment by Daanvm** [comment]
Hi @reyronald, thanks so much!

I just returned from a week long holiday and I'm excited to test this out. I'll let you know how it goes after a couple of PR's!

**Comment by Daanvm** [comment]
_Update after 1 week:_ I've not noticed any glitches or performance issues anymore. Thank you so much for this great update! 🎉

**Comment by reyronald** [comment]
Hello @nickpeirson and @Daanvm , thank you for taking the time to come back and report your experience! It's very valuable to me! I'm glad to know that you are satisfied with how it's working now 🎉 :)
