### ISSUE TITLE
[Bug] Fix Options page so that it fits the screen

### ISSUE THREAD

**Issue by reyronald** [refined-bitbucket/refined-bitbucket#195]
With the newest version of Chrome, the `chrome://extensions` layout was updated. With this layout update, the Options page of the extension is no longer vertically scrollable, so all content that overflows past the screen size is not visible.

![new-options](https://user-images.githubusercontent.com/7514993/38222428-b455a71c-36b2-11e8-8bba-40393e4bab6b.png)

---

Labeling this issue as `help-wanted` and pinging some of the recent active contributors in case someone would like to take a look at it.

@deepakrb 
@drexler 
@clarkd 
@brianespinosa

**Comment by brianespinosa** [comment]
@reyronald go ahead and assign this to me.

**Comment by reyronald** [comment]
@brianespinosa seems like I can't assign issues to non-collaborators :(, but go ahead! The issue is yours.

Thanks for the help! 🙌

**Comment by brianespinosa** [comment]
I still have not had a chance to dig into this fully, but I did check this in Chrome Canary and you **can** scroll there just fine.

**Comment by brianespinosa** [comment]
@reyronald it appears that this might not be something we can fix. The [options form](https://github.com/refined-bitbucket/refined-bitbucket/blob/9cb3607248f6199bee0b81ad62a29204ec9efa37/src/options.html) is being displayed inside of an iFrame. As far as I can tell, the only way we could solve this from within this form is set a height for the form itself and set it to overflow: scroll. We cannot use vh units to define the height of the actual viewport because those units are relative to the iframe.

Since this is fixed in future versions we might have to wait for the fix. Unless you think we should ship a temporary height to our form inside the iframe?

**Comment by reyronald** [comment]
@brianespinosa Wow, great idea on trying with Canary! It didn't occur to me.

So apparently it was a unintended bug by the Chrome team when they redesigned the layout of the `chrome://extensions` page? If that's the case and they already have a fix for it in an upcoming version then I don't think it's worth it to invest time fixing it on our side, right?

**Comment by brianespinosa** [comment]
@reyronald yeah. It looks like it is already fixed in a later version based on what I saw in Canary. And unfortunately I don't think there's a way for us to fix it since we can't target those styles in Chrome above what is running in our settings form iframe. The best we could do would be to set a height on our form with overflow-x: scroll. We would probably want to back that out once a fix was in. Let me know if you think we want to do that for now and periodically check back for a fix. 

I guess the other option would be to make some of the sections of our form click to expand so the user  could collapse areas if they needed to in order to get to all sections. Might end up being a nice feature anyway. And we would not have to back the changes out when the issue gets fixed in Chrome.

**Comment by reyronald** [comment]
Apparently the fix landed in Canary 3 weeks ago here: https://chromium.googlesource.com/chromium/src/+/d4912b2051e7f264221deacb9b7ecfbeadddee9d

Since it is a minor release it will probably land in Chrome in two-three weeks (see "Stable channel" here: https://www.chromium.org/getting-involved/dev-channel). So yeah, I think we rather wait and that's it. 

What you mention avoid the expanding sections, hmm, I guess it could be nice to have yeah

**Comment by reyronald** [comment]
By the way this issue was discussed by the Chromium team themselves here: https://bugs.chromium.org/p/chromium/issues/detail?id=820876. Exact same problem, and apparently it was introduced in the beginning of March.

**Comment by reyronald** [comment]
So as of Chrome's Version 66.0.3359.117 (Official Build) (64-bit), this has been fixed!

Thanks again @brianespinosa for looking into ti!! ❤️
