### ISSUE TITLE
Git blame not aligned with code using larger font size

### ISSUE THREAD

**Issue by Heanthor** [refined-bitbucket/refined-bitbucket#199]
With "Improve the default font-family and size of lines of code in Source view" selected as an option, the popout git blame text does not correspond to the correct line of code. 

Steps to reproduce:

- Click "Blame" on a file in Source view
- Note blame entries line up with code correctly
- Enable "Improve the default font-family and size of lines of code in Source view"
- Note blame view remains unchanged, while code is significantly larger, leading to misalignment

**Comment by Dahaden** [comment]
Probably good to note that "Blame" has been renamed to "Annotate".

**Comment by reyronald** [comment]
Hello @Heanthor and @Dahaden ,

With the recent changes Atlassian made to Bitbucket this feature no longer works because it is targetting selectors that don't exist anymore on the source view page.

Since this was also a very personal preference of mine (the type of font used and the size), I decided to just remove the feature entirely in favor of the new "Custom CSS styles" (#227) that will be coming in the next release v3.11.0. This way, each user of the extension can decide on their own how they would like to manipulate the aesthetics of the page.
