### ISSUE TITLE
Syntax highlighting removes <ins> and <del> tags

### ISSUE THREAD

**Issue by jorcau** [refined-bitbucket/refined-bitbucket#216]
Hi,

It seems that the syntax highlighting removes `<ins>` and `<del>` tags in source code making the strong background color disappear. It can make it a little more difficult to notice diffs on PRs. Here's an example of what it looks like without the extension. You can notice a stronger background color on character diffs.

![screenshot from 2018-05-24 11-55-01](https://user-images.githubusercontent.com/6185428/40478439-57d4aa28-5f49-11e8-972b-69fb9a09f8de.png)

Would that be possible to fix it or add it as an option?

Thanks!

**Comment by reyronald** [comment]
Hello @jorcau ,

This is not the behavior that I see on my end, word diffs show up fine in my browser:

![after](https://user-images.githubusercontent.com/7514993/36613846-18391978-18b1-11e8-901b-5db484a4a2e7.png)

Is it something that happens consistently on ALL of your diffs? What browser are you using?

**Comment by jorcau** [comment]
@reyronald,

Yes, it's happening on all my diffs (mainly Python, Go) except those without syntax highlighting (for instance, .tf files / HCL language).

I tried Firefox 60.0 and Chrome 66.0.3359.170 both without success.

**Comment by reyronald** [comment]
Thanks for reporting @jorcau , there was definitely something wrong (I noticed now on further inspection). Fix will be included in the next patch release.

**Comment by jorcau** [comment]
Sounds good!

Thanks for this great extension @reyronald!

**Comment by LeEnno** [comment]
I'm afraid that this issue was introduced again. No more `ins` and `del` in the markup if syntax highlighting is enabled.

Working with disabled extension:
![working without syntax highlighting](https://user-images.githubusercontent.com/2038814/113109042-e6d2d280-9205-11eb-951b-8b8bcaecc993.png)

Broken with enabled extension:
![broken with syntax highlighting](https://user-images.githubusercontent.com/2038814/113109151-036f0a80-9206-11eb-924f-a7d4748656a0.png)
