### ISSUE TITLE
Autocollapse only works with "Toggle diff text button" enabled

### ISSUE THREAD

**Issue by peterjanes** [refined-bitbucket/refined-bitbucket#221]
Discovered this when I couldn't figure out why my `yarn.lock` files weren't autocollapsing. The behaviour might be by design, but perhaps the preferences UI could reflect it more directly, e.g. disabling the "autocollapse" textarea when "Toggle diff text button" is turned off.

**Comment by reyronald** [comment]
You are absolutely right, the current autocollapsing feature is reusing the toggle diff button to collapse, so if it's not there, it won't work. Like you said this was by design, but was a poor choice for the reasons you just outlined. I'm sorry you wasted some of your time because of that!

I'm going to label this as a bug and the fix should be decoupling both of the features, they should work independently of each other. 

Thanks for reporting!
