### ISSUE TITLE
Enable syntax highlight for side-by-side diff

### ISSUE THREAD

**Issue by andremw** [refined-bitbucket/refined-bitbucket#24]

**Comment by apitzele** [comment]
I was looking at implementing the side by side diff, but I'm not following how the extension.js should get bundled.  Are you using a minifier?   I couldn't tell since its not in source control.  I've never written a chrome extension so I apologize in advance if this is common knowledge.

**Comment by andremw** [comment]
Hey, @apitzele. Thanks for you interest in contributing.
My bad here. I haven't created a "contribute" section in the documentation yet. I totally forgot it.
But in order to create the extension.js I'm using browserify, using the custom command _npm run build_. It's defined in the package.json, if you want to take a look.

Anyway, I'm gonna improve the README to include this information. But if you need any other information, feel free to ask.

Thanks!

**Comment by apitzele** [comment]
That's great Andre, I'll check it out tonight.  Btw, thanks for creating this extension.  I'm still surprised BB doesn't have these features baked in.

**Comment by hk0i** [comment]
I'm not sure this is the right spot but since @apitzele brought up about how to make the chrome extension I thought I'd chime in. I have some very basic jQuery + [Mousetrap.js](https://craig.is/killing/mice) code I wrote that works on bitbucket for changing the tabs in a PR with the 1, 2, 3 keys on the keyboard (this is how the private bitbucket hosting works) I was going to add an enhancement and send the code over but I'm still debating the usefulness of the code I created.

If you definitely want it let me know I can gist it or try to merge it in myself. Right now I have it in a greasemonkey script.

**Comment by andremw** [comment]
@hk0i , it looks interesting! I think you can go ahead and try to add this feature. It will be much appreciated. 
I would just ask you to create another issue if you want to discuss it further (just so that we can have a reserved place to do it).

**Comment by apitzele** [comment]
@andremw , it looks like I don't have permissions to publish a branch to this repo.  Can you authorize me so I can create a PR?

**Comment by andremw** [comment]
@apitzele , you can fork the repository, work on the features in your repo, and then create a pull request to my repo. After you commit some things in your repo GitHub will display a notification asking if you want to create a PR.

**Comment by andremw** [comment]
Done in https://github.com/andremw/refined-bitbucket/pull/30
