### ISSUE TITLE
Python triple quote string is not highlighted correctly

### ISSUE THREAD

**Issue by TomerBG2** [refined-bitbucket/refined-bitbucket#241]
Triple quote string is not highlighted correctly in python and the text inside the string is highlighted as code :

![cropped](https://user-images.githubusercontent.com/31801198/45798319-28d44280-bcb2-11e8-920d-51ff44ea71ab.jpg)

In prism.js it works fine, when trying it on their site https://prismjs.com/test.html it works.

**Comment by bary12** [comment]
Are there any updates on this?

**Comment by reyronald** [comment]
Hello!

Actually this is going to be a `wont-fix`, at least for the time being.

The reason why this works on https://prismjs.com/test.html is because the entire contents of the code is parsed in one go on that playground, but the way the extension works is different. Each line is parsed and highlighted independently, so the extension has no way of telling the current line is inside a multi-line string block or comment. This is essentially the same issue as #150.

Fixing this, is even possible, would require some big efforts that I don't think are actually worth it. If I ever reach a point where there are no other relevant features or improvements in the horizon, I'll take a deeper look into this.

Thanks for reporting!
