### ISSUE TITLE
Support PHP syntax with extensions other than .php

### ISSUE THREAD

**Issue by sunnz** [refined-bitbucket/refined-bitbucket#25]
When looking at the diff of a branch, I can see PHP files with .php extension gets syntax highlighting but not when the extension is .php, e.g. .inc:

Screenshot (first file has .php extension and the second file had .inc):

![Screenshot: first file has .php extension and the second file had .inc](https://www.evernote.com/l/Acfxh84zyu9PjJNNih3XGUR2VlUmZGX-hV4B/image.png)

So I had a quick look at the source code and it seems prism does support matching the `<?php` in the beginning of files to some degree:

https://github.com/andremw/refined-bitbucket/blob/dev/extension/lib/prism.js#L79

Unfortunately I am not familiar with prism.js but would be happy to help if you can point me to the right direction to understand this prism file. I am a web developer with knowledge of PHP (obviously if I am asking for PHP syntax highlighting I guess?) and general knowledge of Javascript and regex.

**Comment by andremw** [comment]
Hi, man. Thanks for your contribution!

I cannot say that I'm too familiar with PHP, but for me it looks like it might be related to this other issue https://github.com/refined-bitbucket/refined-bitbucket/issues/1.

If I'm correct, this would probably not be something too hard to fix.
What do you think? I'll take a look at Prism's doc to see if I find something.

**Comment by reyronald** [comment]
Maybe I am misunderstanding, but this extension chooses the appropriate syntax highlighting style based on the file extension, not the file contents. The reason it is not being highlighted at all is because the extension `.inc` is not included in the list of supported languages.

This could be fixed as easily as adding that new entry in that array, although it would mean that ALL .inc files would have php syntax highlighting, not sure if that could represent a problem for anyone.
