### ISSUE TITLE
Not working at all in Firefox 63.0b4

### ISSUE THREAD

**Issue by peterjanes** [refined-bitbucket/refined-bitbucket#251]
None of the Refined Bitbucket features are working in Firefox 63.0b4: syntax highlighting, auto-collapsing, PR and branch counts, auto-whitespace-ignoring, etc. are all missing. I can see the preferences pane and make changes, but that's about it.

I've tried disabling and re-enabling the add-on in my existing profile, but it hasn't done anything. I've also tried in a clean profile.

(I recognize that I'm running a beta version of the browser that may be buggy; just a heads-up that it may also be an issue with or new restriction that applies to Refined Bitbucket.)

**Comment by peterjanes** [comment]
I suspect it's due to the same change that has affected [Decentraleyes](https://git.synz.io/Synzvato/decentraleyes/issues/313) ([reported as Firefox bug 1489882](https://bugzilla.mozilla.org/show_bug.cgi?id=1489882)).

**Comment by reyronald** [comment]
Hey @peterjanes ! I haven't had a chance to check this out yet. Have you tried using a stable build of Firefox?

**Comment by peterjanes** [comment]
It's okay in Firefox 62. Sorry, I should have indicated that in the initial report.

**Comment by reyronald** [comment]
Hello @peterjanes 	!

Is Firefox's version 63 out of beta yet? If it is, is the extension still not working on it?

I don't want to invest time investigating issues in a non-stable version of any browser. Let me know!

**Comment by blakek** [comment]
It's still not working in `v63.0b14`.

There is a warning:

>Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.

However, other plugins that are working—such as React Developer Tools—also log this same error.  I've enabled add-on debugging, but I don't see any errors logged from this plugin.

How can you debug add-on startup in Firefox v63?  I was wondering if it may log something when starting, but I don't see an option for reloading that plugin.

**Comment by reyronald** [comment]
Hello @blakek ! Thanks for jumping in. I assume `v63.0b14` is still beta right? If that's the case, like I said, I wouldn't worry too much about the extension not working there until that version hits a stable release.

If it turns out that the extension stops working at all in a stable version, then definitely we should take a look.

About the logging, it's unpredictable whether you are going to see anything logged to the console or not, as it depends on what's going wrong and how the extension's code handles that error. If you want to look into it further though, what you should do is set-up a breakpoint or debugger statement right in the first line of code that runs and continue from there.

**Comment by njibhu** [comment]
@reyronald Just to mention that on Firefox Developer Edition, v63 is released. Refined bitbucket is broken for a few month and the Dev Edition is very popular amongst the people who are likely to use Bitbuckets.
Firefox 63 is scheduled to be release tomorrow, everything that would impact this issue is already merged so there won't be any change. The plugin will then be broken on every release channel of Firefox.

**Comment by blakek** [comment]
Verified, this is now broken in the stable release of Firefox (v63).

**Comment by reyronald** [comment]
This is now fixed and released in version v3.13.1. 

Please confirm and let me know.

Thank you all for your patience!

**Comment by blakek** [comment]
@reyronald It's working for me.  Thank you!
