### ISSUE TITLE
Syntax Highlighter strips out percent and some digits (%010d → %0d)

### ISSUE THREAD

**Issue by rschev** [refined-bitbucket/refined-bitbucket#264]
This picture features the same commit (in a pull request) twice. The above is _without_ syntax highlighting enabled, below is _with_ syntax highlighting enabled.

![1544085398](https://user-images.githubusercontent.com/34025055/49572819-e4fdea80-f93c-11e8-898a-543b5a890178.png)

I use this extension mostly to assist in PR reviews, so this is kind of a dealbreaker bug.

Viewing a java file using Firefox 63 on Ubuntu, if it matters for reproduction.

**Comment by reyronald** [comment]
Hey @rschev , this is another issue caused by the Autolinker feature. If you disable it in the Options page (only available on version v3.14.1) you won't get this behavior anymore :)

This is actually a bug in [Prism.js](https://github.com/PrismJS/prism), the library I use for syntax highlighting, not Refined Bitbucket, so I don't have much control over it. This is a minimal reproduction:

https://codesandbox.io/s/5z3q7llw14

I'll try to reach out to the Prism.js guys to see what they have to say about it.

Thanks for reporting!

EDIT: Issue upstream: https://github.com/PrismJS/prism/issues/1721

**Comment by ClementMarrast** [comment]
Hey @reyronald ,

I've still have this bug, would it be possible to update Prism.js library?

Thanks

**Comment by reyronald** [comment]
It was already updated long ago. If you still have it it is either a different case or was re-introduced in a recent version of Prism.js

Can you open a new issue? If you can include a public repo with a pull request that has the problem it'll be much easier to track down.

**Comment by ClementMarrast** [comment]
OK, I'll create a new issue.
Unfortunately, I don't have a public repo.

**Comment by reyronald** [comment]
@ClementMarrast You can create one easily

**Comment by ClementMarrast** [comment]
Ok @reyronald .

It's done here:
https://bitbucket.org/clement-marrast/test/pull-requests/1/change-print-value/diff

I add it to the created  issue.

Thanks
