### ISSUE TITLE
Pull requests not working

### ISSUE THREAD

**Issue by jan-lund** [refined-bitbucket/refined-bitbucket#281]
Tried to create a pull request today but any branch combination resulted in the message no commits that don't already exist in the target branch. It worked when I disabled the Firefox extension.

**Comment by reyronald** [comment]
That doesn't really sound like something related to the extension and I haven't being able to reproduce. 

If you come across this again and you'd like to provide more info, it would be helpful if instead of disabling the entire extension disable feature by feature until you isolate which one might be causing it. If beyond that you can open a public repository where this is reproducible then even better.

Thanks!
