### ISSUE TITLE
Syntax highlighting not working for project repositories 

### ISSUE THREAD

**Issue by alexschwantes** [refined-bitbucket/refined-bitbucket#282]
Have tested it out on bitbucket cloud and the syntax highlighting is working when viewing a shared private repository (with url https://bitbucket.org/user/repo/src/master/app.yaml) but if I try to view a file from a repository in a project (with url like https://bitbucket.org/project/repo/src/master/Server.kt) it doesn't highlight the syntax.

Not sure if the cause is the fact that the repo is in a project or not but I haven't been able to find another reason why it isn't working. could be that Kotlin highlighting isn't working... ?

**Comment by reyronald** [comment]
Hello @alexschwantes !

Refined Bitbucket's syntax highlighting feature only targets diff sections, so it only applies to pull requests, commits and branch compare views.

The regular souce browser you reference is not touched by the extension at all, and this is intentional because it already has first-party support for syntax highlighting, but maybe Kotlin is not one of the supported languages.

**Comment by alexschwantes** [comment]
Thanks @reyronald, I did also try the PR's but they weren't working. I figured out its because the syntax highlighting is only working in the old bitbucket PR view, not their new version. Is there any plans to support the new PR view?

**Comment by reyronald** [comment]
@alexschwantes There is, checkout this issue #252
