### ISSUE TITLE
Remove "Default Merge Startegy" or let users disable it

### ISSUE THREAD

**Issue by gronostajo** [refined-bitbucket/refined-bitbucket#288]
This feature was requested in #90 and introduced in #91. I think it's counter-productive, though. Bitbucket has its own, per-repository setting for this. Maybe it was introduced after #91? I don't know.

![image](https://user-images.githubusercontent.com/1347866/58702764-fcc3a200-83a6-11e9-853b-f8eed1989c21.png)

Refined Bitbucket overrides this setting for all repos. It leads to mistakes if you work with multiple repos that prefer different merge strategies. IMHO it would be better to let repository owners choose their preferred strategy. So I'd suggest to:

- Remove this feature altogether in favor of the built-in one, or
- Let users opt out of overriding this setting and respect the default

**Comment by reyronald** [comment]
@gronostajo 

This feature was originally requested to Atlassian by the community on Feb. 23, 2017 [here](https://bitbucket.org/site/master/issues/13895/default-merge-strategy). Bitbucket's product manager stated that it wasn't something they were prioritizing at the moment, despite the feature request having so many votes, so I added it as a feature to Refined Bitbucket on December 2017 (#91).

It only became available on Bitbucket around May 2018, but until then there was no confirmation if they were ever going to implement this themselves or not. So calling it counter-productive is a little bit disrespectful in my opinion, especially since I know that many people benefited from it.

So far no one had complained about the conflict you bring up on this issue, and that's why it hadn't being resolved.

I'll add the possibility of disabling it in the upcoming update.

Thanks

**Comment by reyronald** [comment]
Released in v3.17.0

**Comment by gronostajo** [comment]
Hi, thanks for the fix! I didn't mean to be disrespectful, I only meant that it's counter-productive right now, when this feature is available out of the box. I suspected that it may have been added there later, hence the "I don't know" part in original post.
