### ISSUE TITLE
Create a tooltip for the disabled merge button in pull request window

### ISSUE THREAD

**Issue by andremw** [refined-bitbucket/refined-bitbucket#32]
By default the minimum number of pull request approvals is 2, and until then the merge button gets disabled. This can be taken as a bug in Bitbucket's UI, so the extension should show a tooltip explaining that the extension disabled it when the user hovers/clicks the button.

**Comment by hk0i** [comment]
Instead of a tool tip maybe change the caption to say something like "Waiting for Approvals"
I'm not sure if you can find the right words small enough to fit in though. Maybe even just "Merge (@#)" where the # in parens is the number of approvals needed.

"Merge (@2)"
or
"Merge (2 Approvals Needed)"
if the size fits well.

**Comment by andremw** [comment]
Sorry for the delay. I was in vacation and didn't take a time to look at it. I'll work on it as soon as possible.
