### ISSUE TITLE
Refined Bitbucket is causing Firefox to slow down

### ISSUE THREAD

**Issue by PLWpl** [refined-bitbucket/refined-bitbucket#351]
Hi, 

For a while now (about two months) I've been having issues with Refined Bitbucket. Whenever I enter PRs, a browser's bar appears informing me that 

<img width="1662" alt="image" src="https://user-images.githubusercontent.com/35236340/80210647-62aabf00-8634-11ea-9ddd-b8405fb7baef.png">

Only stopping it or temporarily disabling helps - waiting doesn't.

The issue is present no matter the PR, if it has many files or just a few, a long ones or one-liners. 

Please let me know if you need any further info from me to look into this. 

Refined Bitbucket version: 3.20.0.
Firefox: up-to-date, right now 75.0.

**Comment by jwallet** [comment]
i stumbled upon this issue, my case was index.js (minifed) caused the script to fail. 
if I add index.js to the file I want to delete using rbb bitbucket is not freezing anymore, adding it to the files to collapse does nothing. if index.js is not minified it's working too.

 it's caused by highlight which tries to read the line. A line that represents the whole app.

@reyronald

**Comment by jwallet** [comment]
it affects chrome as well. chrome freezes totally, firefox freezes the render but you can still change tab or scroll. chrome after 10secs sucessfully render, firefox crashes.

**Comment by jwallet** [comment]
updating prism to latest : 1.20 fixes the issue
