### ISSUE TITLE
Chrome extension requesting permission to read browsing history

### ISSUE THREAD

**Issue by jinglesthula** [refined-bitbucket/refined-bitbucket#381]
Not sure if this permission was recently added, or if Chrome just recently started notifying users, but when I started the browser I saw that it is requesting permission to "Read your browsing history", and to accept permissions or remove the extension.

This is a bit of a turn-off for me, as I've been enjoying the extension and am not sure why it needs to now start accessing my browser's history to run js on BB pages.  I think for now I'll keep it installed, but disabled.

If there's a way to weigh the cost/benefit of the permissions against any added functionality that requires them, it would be great to avoid asking for them.  I doubt Chrome extensions will give developers the option to have "optional permissions" and detect what has been granted and provide as much functionality as can be achieved with whatever permissions have been granted, but until then, less is more.

**Comment by reyronald** [comment]
This warning started to pop up because of the added `webNavigation` permission. Its description is:

> Use the chrome.webNavigation API to receive notifications about the status of navigation requests in-flight.

You can read about it here: https://developer.chrome.com/extensions/webNavigation

This is necessary ever since Atlassian recently started using the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History) to handle route navigations rather than having server-rendered views for all their pages, as it used to be. Without it, the extension would not be aware of these route transitions and wouldn't be able to run the appropriate JS on BB pages.

If you read through the Chrome documentation I posted above, you'll notice that this doesn't mean that the extension will be able to extract all your browser history, it just means that when Bitbucket uses the `history` object, it'll be notified.

It's also worth noting that the extension is onlly allowed to run code in the `bitbucket.org` domain, and you can confirm this yourself in your browser.

![image](https://user-images.githubusercontent.com/7514993/94625077-e6bd3e80-0285-11eb-809b-7dad7e76e2f6.png)

**Comment by chestozo** [comment]
this one is also scary:
![image](https://user-images.githubusercontent.com/498934/95744794-9b9b2680-0c9c-11eb-8e2c-c8e28c1afa97.png)

what you may need to update in BB profile?

**Comment by reyronald** [comment]
That one has always been there. 

If the extension cannot change the data on bitbucket.org then it can literally do nothing
