### ISSUE TITLE
Add option to enable syntax highlighting on hosted bitbucket servers

### ISSUE THREAD

**Issue by tibuntu** [refined-bitbucket/refined-bitbucket#39]
Hey guys! Awesome work here! 
I would really like to have an option to use another URL than 'bitbucket.org'. 

Currently the only solution to get it partially working (Seems to work only for key mappings) on self hosted Bitbucket servers is to recompile the plugin after changing line 21 and 34 in extension/manifest.json.

**Comment by asiderop** [comment]
Agreed, this should be a configurable option for the extension.

**Comment by asiderop** [comment]
Maybe I am wrong (I do not know a lot about Chrome extensions), but supporting self-hosting BitBucket servers would require permissions for accessing all tabs and all websites.

Then the extension, as loaded on every page request, would check if the URL matches its configured URL and programmatically load the scripts only when there is a match.

Is there a less intrusive way to accomplish this?

**Comment by reyronald** [comment]
@asiderop That's exactly the approach I am experimenting with, and no, I don't think there's any less intrusive way to accomplish it sadly.

But that small logic check logic is pretty lightweight. I'm thinking it wouldn't be so consequential anyway and the payoff would be very appreciated, because we've been receiving requests for this feature since the start! The extension would have a lot more users if we could accomplish it, so I'm going with that approach for the time being, hehe.

I'm by no means an expert on Chrome extensions either, so if anyone has something else to add go ahead!

**Comment by reyronald** [comment]
@asiderop @tibuntu [Just submitted a pull request for it](https://github.com/refined-bitbucket/refined-bitbucket/pull/54)! However I don't have access to an instance of Bitbucket server, so I couldn't test in an actual REAL scenario, it would be great if any of you could try it out in your case and report back if it works as expected, would definitely appreciate that!

**Comment by tibuntu** [comment]
@reyronald @asiderop i just gave it a try!

I've checked out your feature branch and re-compiled the extension. Directly after installing it chrome notifies about "There were warnings when trying to install this extension:
Unrecognized manifest key 'applications'."

I've configured the URL of our Bitbucket server (using HTTPS of course) but it doesn't work. Unfortunately i can't tell why. Is there anything from the developer tools that you could make use of?

Edit: But switching the tabs within a PR using '1' '2' '3' is working!

**Comment by reyronald** [comment]
@tibuntu  You can ignore the Unrecognized manifest key 'applications' error, it has to do with some keys in the manifest file that are there so that the extension can also work on Firefox, so Chrome doesn't recognize it.

Can you tell me what form your URL has? And yeah, from the chrome://extensions page, click "background page" in Inspect views. Also, with the options view opened, right-click the modal and inspect from there, do you see any console errors in both devtools?

Also, what version of chrome are you using?

**Comment by reyronald** [comment]
@tibuntu Just say your edit, and wow, that's so strange! If the hotkeys are working it means that the content scripts were successfully injected in your Bitbucket server domain... so everything else from the extension should also work! 

Is by any chance the PR you are checking really big? If it is can you check a smaller one? Try refreshing too just in case, haha.

**Comment by tibuntu** [comment]
@reyronald Thanks for clarification!

the URL is `https://git.ourcustomer.com`
Chrome version: 61.0.3163.100 (64-Bit)

And the only error that i can find in the developer tools is:

`Error in event handler for (unknown): TypeError: Cannot read property 'msg' of undefined
    at chrome-extension://fjccjnfkdkdmjohojoggodkigkjkkjhl/contentscript.js:41:11`

Just to be sure: We are mainly working with YAML and the plugin should bring YAML Syntax Highlighting, correct? Also marking a word to see all occurrences does not work.

**Comment by reyronald** [comment]
@tibuntu Yes, the extension supports YAML. 

I just commited something, fetch/pull the changes, enable/disable the extension, then reload it, try again and let me know! 

EDIT: Readd the URL in the options box after reloading it by the way

**Comment by tibuntu** [comment]
Still doesn't work. Now i got these error messages:

```
Uncaught (in promise) Error: waitForRender: Couldn't find the element .ellipsis
    at setInterval (extension.js:826)

extension.js:826 Uncaught (in promise) Error: waitForRender: Couldn't find the element .bb-udiff
    at setInterval (extension.js:826)

extension.js:826 Uncaught (in promise) Error: waitForRender: Couldn't find the element .diff-container 
    at setInterval (extension.js:826)

extension.js:826 Uncaught (in promise) Error: waitForRender: Couldn't find the element .bb-patch
    at setInterval (extension.js:826)

extension.js:826 Uncaught (in promise) Error: waitForRender: Couldn't find the element .ellipsis
    at setInterval (extension.js:826)

extension.js:826 Uncaught (in promise) Error: waitForRender: Couldn't find the element .bb-udiff
    at setInterval (extension.js:826)

extension.js:826 Uncaught (in promise) Error: waitForRender: Couldn't find the element .diff-container
    at setInterval (extension.js:826)

extension.js:826 Uncaught (in promise) Error: waitForRender: Couldn't find the element .bb-patch
    at setInterval (extension.js:826)
```

**Comment by reyronald** [comment]
@tibuntu Those errors are actually coming from the extension and they show up in any page that's not a pull request or commit (I know, I have to take care of that), so the feature itself of loading the content scripts in the configured URL in the options is working wonderfully! That was also evidenced by the fact that you got the hotkeys working too.

So now that we got that out of the way, the fact that you are not seeing any syntax highlighting must be another issue entirely. What comes to my mind is that the layout of your Bitbucket Server doesn't match the current layout of bitbucket.org and the one expected by the extension, there must be some differences in the DOM I bet.

[This is what you have, right?](https://www.atlassian.com/software/bitbucket/server), there seems to be a trial available, I'll try to install it and test it myself. I wanna mirror your instance as much as possible to see if I can catch why it's not working for you, is there anything I should take into account? is there any specific version or configuration that you are using?

**Comment by reyronald** [comment]
Ok, so I finally got around to install the trial of Bitbucket Server on my own machine And to my surprise, Bitbucket Server is an entirely different product. I had just assumed that it was the in-house version of Bitbucket Cloud, but that's not the case. After investigating further, I stumbled upon the following info:

> **Why aren't the Server and Cloud features the same?**
> Bitbucket Server (previously known as Stash) was first released in May 2012 as an enterprise-grade, high performance, self-managed Git repository hosting and collaboration tool. It was built from the ground-up for self-managed deployment. Bitbucket Cloud (previously known as Bitbucket) was acquired by Atlassian in 2010 and was purpose-built for the multi-tenant public cloud. **As a result, Bitbucket Cloud and Bitbucket Server had different technical architectures with different feature roadmaps.** Over the past 2 years, much progress had been made in bringing conceptual and functional parity to the products, and work will continue to improve upon this.

[Source](https://confluence.atlassian.com/bitbucketserver/bitbucket-rebrand-faq-779298912.html#BitbucketrebrandFAQ-Whyaren'ttheServerandCloudfeaturesthesame?)

Which basically means that this extension is not compatible with Bitbucket Server 😞 . I'll have to label this issue as `wont-fix` for the time being and decline the pull request. The correct way to go around this would be to create another extension entirely for Server, and maintain it separately. 

Since it is not free, this would have to be done by someone that actually uses and has access to a Bitbucket Server instance, and that's why it can't be me :/.  This is obviously a dissapointment because this has been a long requested feature, my apologies!

**Comment by tibuntu** [comment]
Sorry for the late reply. Thank you for digging deeper! Very unfortunate ;)
