### ISSUE TITLE
Fix performance issue for pull requests with lots of files

### ISSUE THREAD

**Issue by andremw** [refined-bitbucket/refined-bitbucket#43]
When working with big pull requests the screen becomes unresponsive while the plugin is trying to highlight everything.

Some ideas:
- Use Prism's web worker feature to highlight asynchronously;
- Change the plugin to highlight only some pixels above and below the viewport. This one looks better to me.

**Comment by reyronald** [comment]
Bitbucket has a predefined limit to how many diffs it will load into a single Pull Request initially. That way they keep the overall load time somewhat constant no matter how big the PR is, so in theory the page shouldn't really slow down very much even if there are many files changed.

Before merging #77 , the previous implementation of syntax-highlighting had some flaws that would make the performance impact of the feature bigger, the bigger the PR was. Most of those flaws (if not all) were addressed in #77, so the responsiveness should have been greatly improved.

Since this issue is referring to that previous implementation, I'm going to close it for now while we gauge how the extension behaves now. It's still possible that we might need to address other performance issues in the future, but they should be contextual to the implementation in place at that moment.
