### ISSUE TITLE
Publish to addons.mozilla.org

### ISSUE THREAD

**Issue by awendland** [refined-bitbucket/refined-bitbucket#89]
Now that #40 has merged and the extension lints as compatible with Firefox addons (as reported by https://www.extensiontest.com/test/e2063b50-d897-11e7-ab7b-6bf57e79ff4d), this extension would be great for everyone who leverages the Firefox Add-ons store.

It looks like you need to create a Firefox account and then can publish it. How can us Firefox users help you out with that process and its maintenance?

-A long time Chrome user who is in a honeymoon phase with Firefox Quantum (but still trying to replicate the great experience from particular Chrome extensions, like this one! Thanks!)

**Comment by reyronald** [comment]
Hey @awendland , the reason why this extension is not yet published in the Firefox store is because... well, no one had asked! Hehe.

If this extension as it is is really compatible with Firefox like you and others have pointed out it would be amazing! The transition could be done in minutes I suppose, let's hope that's the case. I'll finish two more issues that I'm working on right now then I'll look closely into this. With the Firefox Quantum fever going on I'm sure the rest of our userbase would be glad, and maybe I could migrate myself as well! 

If you absolutely can't wait though, you could load this extension into your own Firefox instance in development mode easily, you would only need to clone the repo, checkout the `dev` branch, run `npm install` then `npm test`, and you're good to go, all the code would be compiled into the `/extension` folder, which you would then load into Firefox somehow (I've never done this myself, but should be easy enough and well documented in some official documentation).

Thank you for the suggestion and for making yourself available! I'll keep you posted on the progress.

**Comment by awendland** [comment]
@reyronald Thanks for jumping on the case! Yes, you should definitely check out Firefox Quantum. It's finally a browser that really contends with Chrome; maybe Chrome's monopoly trend will start to healthily recede a little.

I just loaded the extension using the temporary extensions process at https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Your_first_WebExtension#Installing. Things seem to be working great (though I'm only intimately familiar with a small subset of the extensions functionality, mainly around syntax highlighting)! No console errors that I could find. The only complaint is from the Firefox extensions page which I've screenshotted here:

<img width="730" alt="screen shot 2017-12-04 at 11 26 55 pm" src="https://user-images.githubusercontent.com/1152104/33590071-e6d75d9a-d94a-11e7-800d-969e5108347e.png">

**Comment by reyronald** [comment]
That's fine! It's an improvement over something from the Google Extension API that apparently Mozilla hasn't implemented themselves in Firefox, but they are falling back to the traditional behavior, so should be fine.

I'll test all the features myself when I get around to it, in the meantime you can enjoy the ones that you use!

**Comment by reyronald** [comment]
Hey @awendland , the Firefox Add-on is already officially published! Check it out here: addons.mozilla.org/en-US/firefox/addon/refined-bitbucket-/.

Let me know if you find any issues with it.
