### ISSUE TITLE
[FR] Merge commit message template

### ISSUE THREAD

**Issue by ikornienko** [refined-bitbucket/refined-bitbucket#97]
Bitbucket Cloud has the corresponding feature request: [Issue #14101](https://bitbucket.org/site/master/issues/14101). It seems that it won't be implemented any time soon.

With Bitbucket Cloud now supporting Squash merge strategy for PRs, the commit message becomes really important (vs having some generated commit message for merge commits). I believe for many teams it would make more sense for Squash to put PR title as a first line, instead of default Bitbucket's suggestion `Merged in ${PR_SOURCE_BRANCH} (pull request #${PR_NUMBER})`.

refined-bitbucket can support simple text configuration for a template where users can use `${PR_TITLE}`, `${PR_SOURCE_BRANCH}`, `${PR_TARGET_BRANCH}`, `${PR_NUMBER}`, `${APPROVED_BY_LIST}` variables to inline the corresponding data to generate a commit message for merging the PR.

**Comment by reyronald** [comment]
Hi @ikornienko , thank you for your contribution! I'll look into it !

**Comment by fawques** [comment]
Hi, while you look into this, could you also implement pull request templates? There is already a [chrome extension](https://github.com/tcrammond/chrome-pullrequest-templates), but not a firefox one.

The [corresponding bitbucket feature request](https://bitbucket.org/site/master/issues/11571/custom-pull-request-description-template) has > 200 votes but almost no response from the atlassian team.

**Comment by reyronald** [comment]
Hi @vguzmanp , definitely !

**Comment by reyronald** [comment]
@vguzmanp Can you open another issue for that please? So that we can track it separately.

**Comment by alonl** [comment]
Good call. I would also be very happy if I could add the Description of the Pull Request to the merge commit message. 

Thanks a lot for this great extension!

**Comment by deepakrb** [comment]
There seems to be a bit of work to do speccing this out @reyronald. I know we would find it massively useful so I would love to see this feature in RB. Can I be of any help with this?

**Comment by reyronald** [comment]
Hello @deepakrb ! Nice to see you again over here :)

Well, how would you like this feature to work from the user's perspective if it was implemented? There has been a few suggestions but just curious if you and your team think differently

Maybe I can work on a proof of concept in the following week.

**Comment by deepakrb** [comment]
Nice to be back @reyronald 😄 

I was fully on board with @ikornienko's suggestions, as in a system similar to the current Pull Request template system where you can commit a Merge Message markdown file (with variable injection) to the root directory of the project which would be inserted into the merge message.

Just speaking personally, we have a policy where we currently manually remove the first "Merged in ..." comment for squashes because it really has no use to us. It makes logging and reverting commits much more difficult when someone forgets to do it and we can't easily read the feature merge.

Taking it one step further we could also possible make those variable available in the pull request template, what do you think?

**Comment by reyronald** [comment]
Hey everyone, this feature is included in version 3.13.0. Please try it out and let me know what you think and if you find any issues with it.
